# frozen_string_literal: true

source 'https://rubygems.org'

gem 'cookstyle'
gem 'highline'
gem 'inspec'
# gem 'inspec-bin'
gem 'chef-cli'
gem 'inspec-core'
gem 'kitchen-inspec'
gem 'kitchen-sync'
gem 'kitchen-vagrant'
gem 'rake'
gem 'rubocop'
gem 'rubocop-rake'
gem 'test-kitchen'
